In [16]:
import numpy as np

x1 = np.array([-1, -1, 1, -1, 1, -1, -1, 1],dtype="float")
x2 = np.array([-1, -1, -1, -1, -1, 1, -1, -1],dtype="float")
x3 = np.array([-1, 1, 1, -1, -1, 1, -1, 1],dtype="float")

patterns = np.array([x1,x2,x3])

def init_weights(patterns):
    dim = patterns.shape[1]
    w=np.zeros((dim,dim))
    
    for i in range(dim):
        for j in range(dim):
            s = 0
            for pattern in patterns:
                s += pattern[i]*pattern[j]
            w[i][j]=(1/(patterns.size)) * s
    return w

def recall(pattern):
    dim = pattern.size
    count = 0
    
    previousPattern = np.zeros(dim)
    while True:
        out = np.zeros(dim)
        for i in range(dim):
            s = 0
            for j in range(dim):
                s += w[i][j]*pattern[j]
            if s >= 0:
                sign = 1
            else:
                sign = -1
                    
            out[i]=sign
        
        pattern = out
        print(pattern)
        
        if check_True(pattern):
            print ("It took:",count,"nr of iterations")
            break
            
        elif np.array_equal(pattern,previousPattern):
            print("Local minimum found in iteration:",count)
            break
        
        previousPattern=pattern
        count += 1
        

def check_True(predicted_pattern):
    solved = False
    for i in range(patterns.shape[0]):
        if np.array_equal(patterns[i],predicted_pattern):
            print("True!")
            print("Pattern matches stored pattern nr:",i+1)
            solved = True
    return solved
        

    
w = init_weights(patterns)

recall(x1)
recall(x2)
recall(x3)

[-1. -1.  1. -1.  1. -1. -1.  1.]
True!
Pattern matches stored pattern nr: 1
It took: 0 nr of iterations
[-1. -1. -1. -1. -1.  1. -1. -1.]
True!
Pattern matches stored pattern nr: 2
It took: 0 nr of iterations
[-1.  1.  1. -1. -1.  1. -1.  1.]
True!
Pattern matches stored pattern nr: 3
It took: 0 nr of iterations


In [18]:
x1d=np.array([1, -1 ,1, -1, 1, -1, -1, 1],dtype="float")
x2d=np.array([1, 1, -1, -1, -1, 1, -1, -1],dtype="float")
x3d=np.array([1, 1 ,1, -1, 1, 1, -1, 1],dtype="float")

def count_minimums():
    
    minimas = np.array([])
    iterations = 0
    while(iterations<500):
        
        pattern = np.array([1,1,1,1,-1,-1,-1,-1])
        np.random.shuffle(pattern)
        dim = pattern.size
        
        while True:
            out = np.zeros(dim)
            for i in range(dim):
                s = 0
                for j in range(dim):
                    s += w[i][j]*pattern[j]

                if s >= 0:
                    sign=1
                else:
                    sign=-1
                    
                out[i]=sign

            pattern = out

            if np.array_equal(pattern,out):
                if(minimas.size>0):
                    contains = False
                    for i in range(minimas.shape[0]):
                        if(np.array_equal(pattern,minimas[i])):
                            contains = True
                    if not contains:
                        minimas = np.vstack((minimas,pattern))
                        print(minimas.shape[0])
                else:
                    minimas = np.array((pattern))

                

                break
        iterations+=1
        

recall(x1d)
recall(x2d)
recall(x3d)

#count_minimums()

[-1. -1.  1. -1.  1. -1. -1.  1.]
True!
Pattern matches stored pattern nr: 1
It took: 0 nr of iterations
[-1.  1. -1. -1. -1.  1. -1. -1.]
[-1.  1. -1. -1. -1.  1. -1. -1.]
Local minimum found in iteration: 1
[-1.  1.  1. -1.  1.  1. -1.  1.]
[-1.  1.  1. -1. -1.  1. -1.  1.]
True!
Pattern matches stored pattern nr: 3
It took: 1 nr of iterations


In [21]:
x1dd=np.array([1, 1 ,-1, 1, 1, -1, -1, 1],dtype="float")
x2dd = np.array([1, -1, 1, -1, 1, 1, 1, -1],dtype="float")
x3dd = np.array([-1, -1, -1, -1, -1, -1, -1, -1],dtype="float")

recall(x1dd)

[ 1.  1.  1.  1.  1. -1.  1.  1.]
[ 1.  1.  1.  1.  1. -1.  1.  1.]
Local minimum found in iteration: 1
